language: java
sudo: required
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
before_install:
- sudo apt-get install net-tools
- sudo apt-get install python-pip
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: "./gradlew clean build"
script:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ];then git checkout master;git remote set-url
  origin "https://$GITHUBKEY@github.com/yahoo/parsec";./gradlew release; fi
- test "${TRAVIS_PULL_REQUEST}" != "false" || test "${TRAVIS_BRANCH}" != "master"
  || ./gradlew bintrayUpload --info
- sudo pip install mkdocs
- mkdocs build
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ];then git fetch && git fetch origin gh-pages:gh-pages;mkdocs
  gh-deploy --clean;fi
after_success:
- "./gradlew coveralls"
## reference : https://docs.travis-ci.com/user/environment-variables/
## global vars will be auto updated after run `travis encrytpion ...`
env:
  global:
  - secure: t/YmohP7hMuyGl6DcuRgPwUpm673SNKeFDegnEhikAK3155uMjQkbwqcbqzM6KTco0TVOVvoCDEp7C8DuJit8IYNgfXZdCo4nFS+XzzG8OtIy7RBRSWlwn/VaypTaqq6TFO+0Lvmo6oIyaT14D5M1eFwxpNie7Pjn9ycvZdMMcK/aUfTgRjvNiyFhZIT178JmzjdfpXsuTCp0eeK9mi/sQvT6zITIuyR9N61nvvcJiNENRidojH8jO8T1gL9QwcUrlJO95JuZ4o2uzFmlRxnPQj0qNJc9rEJJei9qFHvSz096FAxZFw9mE2OmFSiPmrn46nnxutfN9xsHn9ki3o+SjTlnY4h74fEcU/c4buFgoqRRHGRREQyDBbizMm3QL43Ze0S/bLvFhHY2K9tEhCYWmQWckKDPs+LbDtvfgyDyZpxovioMykmwSXbAB5TpVTtUG7Bit7KWj6dYwTVOYxPC1Do+JW2CsD9F8NR6yBTnmV5WF4tGPux2WOH6x3SkYr361J+eXA1hUF/VDWmATI0wsAlE/ZF14Efl05hle6hlraG/xzeNDbJA001QA4FWgDQO1Sv0TeJeeH7ydRUXcouCKJ+jo2XcLqBmL7SIW3We/55p3y4Y2q/0lTefOVECdTcfHgjB5monhyINIfkozotuZ+ugjzl6ON+nBxk07chvXE=
  - secure: dnjdsBcnrLAV0fNC/C9W0F6s2eU3ePLNfl9jGanBis9nZvyPNvAVyouaAv8AoSqaaRrQU6izf/wl0D2VhjSVksQpOwDj4t1EjrYi8S/FKYk3Vbsc4/1q9/sXzZBUYEYAAy2mce50lC0knBlCqsEcFUKoNlA7pbvUjE/uOknCp8zioXf1Cjz3aMfXdX5U/r/5I4FOYulBoDt9PGOlKe3jylO14AQCSWEnuT6sXe19VxtVkMShrWPloJJa3bYoMvt+lMqbjTHCWB0xjCYhQEPP9Qah8WgrXGGpcOYsu7JtXbzziCDGdLRPz/CFcukeOsytysG5GiNheNJQ9YnCw6o+TmOD9ym2ZyVVbUty2Jkh/xYfR/fRaOrG+rSwgGODv1Oc66G8MZOzo4bIeS1NcO5w0HHlR+luagljI5Sf7oydUj87SwW04oS/vwnm1RAXEHIk8jhyPIBiBekyRWnIRVtZZPjSs9Z8Mf3CMQjQ3wcxmpmBMzS8CnkPqtvorWxXF7rGkFaUXZNYooL5uIcnFi9cIjpanxhnAEIuMn7E+sYiCfxYPxYSkq8bC44DeLXPtL9LbXcZVtK8kxLP4Z3Eoy1nev4OykJthC0XKu3XNDufpGRh/47le/+syhIb5T4tOAtiYF95w9pGOBZ0KlfTP2jMOLiRGliaN4fp8+T/9Q9E/CM=
  - secure: aSeOpDW/ronZ608I2RYnaEdNC3x/haTDtmsHacqxDvJ0EwsJxc8qJRrbvD2IX6wAaZ/8wfKGobI1sV/zMQfMoONrGZUo4lDwek80RQc6r9KMFGIe2nC1cJ2TuI2/f0Tksta5uxxEMow++SgJvPa4HEL9XuVp6+bv2mOjbVZ3B8DbMPWNOgipPsPaNGRKRL4affgXbqzcoYhMYou4L4dVAuFKYapUX+VY4s4cFm07qwebGfCZVf3tIUp6l7mOu0xRY97MnO3WespDOdQbzYx1vTfO80q41JDiHSsLwSSqAm3FlR7ai4bJdYHODjXHCPt+s6NbUtdOWzatv240Xh8vV2BUw6dl1i9VldY2RMrvsffmby0EEIORpyZqtl2YwW47vdqDIZH/QlDgySz1pExPqa/E5+rbFVIvPdz/u/rgJAGdfz0kzIXUUs/SDWS+cxtZ3a2LlTX+MLcC+/WQ83pME98mqqcosp2Q4SgsvnP54PLLWoGY4/EXcgwucO4hFO9bmqLPqt54pCcaYX96+JKkNEwU8OVTMPPcw3SyOWSreQx9EUBgL7RSo1wFoD5/BDn659ZB5CNscYFEIPOqgXGDSQqO6fhCj7tKLqD3+HRoWZ788mC4nBdPHNgTAi98vJZSaDfyWK37zAApnWYoRQkSOyJMVLMeaaB8tScZDJok+4Y=
branches:
  only:
  - master
dist: trusty
